site_name: Akvo Knowledgebase
repo_url: https://github.com/akvo/knowledgebase
theme:
  name: null
  custom_dir: mkdocs_docskimmer

piwik: 6ff13965-650f-49d6-8a20-a2c7b7c4c4d9

i18n:
  - name: French
    icon: 🇫🇷
    code: fr-FR
    code2: fr
  - name: Spanish
    icon: 🇪🇸
    code: es-ES
    code2: es
