site_name: Knowledgebase
repo_url: https://github.com/akvo/knowledgebase

markdown_extensions: 
  - attr_list
  - md_in_html


plugins:
  - tags
  - search:
      lang: 
        - en
        - fr
        - es

  - mkdocs-video

# theme:
#   name: null
#   custom_dir: mkdocs_docskimmer
theme:
  name: material
  logo: img/logo1.png
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    scheme: default
    primary: black
    # scheme: default
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode
    # scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode

extra_javascript:
  - javascripts/extra.js
  - javascripts/reamaze.js

piwik: 6ff13965-650f-49d6-8a20-a2c7b7c4c4d9

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<support@akvo.org>
    - icon: fontawesome/brands/github
      link: https://github.com/akvo
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Akvofoundation
  alternate:
    - name: English
      link: /
      lang: en
    - name: French
      link: /fr/
      lang: fr
    - name: Spanish
      link: /es/
      lang: es
  # analytics: 
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.


i18n:
  - name: French
    icon: 🇫🇷
    code: fr-FR
    code2: fr
  - name: Spanish
    icon: 🇪🇸
    code: es-ES
    code2: es

nav:
  - HOME: 'index.md'
  - 'RSR':
    - 'What is RSR?': 'rsr/index.md'
    - 'Programs': 'rsr/program_vs_project.md'
    - 'Accessing RSR': 'rsr/access.md'
    - 'Project editor': 'rsr/project_editor.md'
    - 'Results framework': 'rsr/results_framework.md'
    - 'M&E Indicator Updates': 'rsr/indicator_updates.md'
    - 'Enumerators': 'rsr/enumerators.md'
    - 'User management': 'rsr/user_management.md'
    - 'Standard Reporting': 'rsr/standard_reporting.md'
    - 'IATI Reporting': 'rsr/iati_reporting.md'
    - 'Quickstart Guides': 'rsr/guides.md'
    - 'APIs': 'rsr/apis.md'
    - 'FAQs': 'rsr/faqs.md'
  - 'FLOW':
    - 'What is Akvo FLOW?': 'flow/index.md'
    - 'Online Workspace': 'flow/workspace.md'
    # - 'Folders': 'flow/folders.md'
    # - 'Surveys': 'flow/surveys.md'
    # - 'Forms': 'flow/forms.md'
    # - 'Question Groups': 'flow/groups.md'
    # - 'Questions': 'flow/questions.md'
    # - 'Devices': 'flow/devices.md'
    # - 'Data': 'flow/data.md'
    # - 'Resources': 'flow/resources.md'
    # - 'Maps': 'flow/maps.md'
    - 'FLOW App': 'flow/app.md'
    - 'Data collection': 'flow/collection.md'
    - 'Data monitoring': 'flow/monitoring.md'
    - 'Akvo Caddisfly': 'flow/caddisfly.md'
    - 'Quickstart Guides': 'flow/guides.md'
    - 'APIs': 'flow/apis.md'
    - 'FAQs': 'flow/faqs.md'
  - 'LUMEN': 
    - 'What is Akvo Lumen?': 'lumen/index.md'
    - 'Connect': 'lumen/connect.md'
    - 'Data types and groups': 'lumen/types.md'
    - 'Data Transformations': 'lumen/transform.md'
    - 'Column Functions': 'lumen/functions.md'
    - 'Merge Datasets': 'lumen/merge.md'
    - 'Visualization Types': 'lumen/visualize.md'
    - 'Maps': 'lumen/maps.md'
    - 'Charts': 'lumen/charts.md'
    - 'Pivot Tables': 'lumen/tables.md'
    - 'Dashboards': 'lumen/dashboards.md'
    - 'Share': 'lumen/share.md'
    - 'Working with FLOW data': 'lumen/flow_data.md'
    - 'User management': 'lumen/user_management.md'
    - 'FAQs': 'lumen/faqs.md'
  - CONTACT US: 'contact.md'

